// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhcyxvraspyajsddstin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoY3l4dnJhc3B5YWpzZGRzdGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMTQ2MTIsImV4cCI6MjA1NTc5MDYxMn0.bwJIjTYSpQxgmElrj9czqBeKDsveYpRhQguQwUGJZ3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);